//
//  UISplitViewController.m
//  UIKitCore
//
//  Copyright (c) 2009-2018 Apple Inc. All rights reserved.
//

#import "UISplitViewController.h"
#import "UISplitViewControllerImpl.h"
#import "dyld_priv.h"
#import "UIDevice.h"

@interface UISplitViewController () {
    __strong id<UISplitViewControllerImpl> _impl;
    BOOL __lockedForDelegateCallback;
}

@end

@implementation UISplitViewController

- (void)_commonInit {
    dyld_build_version_t ios8 = { .platform = PLATFORM_IOS, .version = 0x00080000 };
    if (!dyld_program_sdk_at_least(ios8) && [[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
        [NSException raise:NSInvalidArgumentException format:@"UISplitViewController is only supported when running under UIUserInterfaceIdiomPad"];
    }

    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{

    });
}

- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    self = [super initWithNibName:nil bundle:nil];
    if (self) {
        [self _commonInit];
    }
    return self;
}

- (instancetype)initWithCoder:(NSCoder *)coder {
    self = [super initWithCoder:coder];
    if (self) {
        [self _commonInit];
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-value"
        // The code generated by clang for ivar _impl will call retain/release one more time
        [self->_impl initWithCoder:coder];
#pragma clang diagnostic pop
        
    }
    return self;
}

@end
